---

- name: Create CNI Container config
  command: /usr/bin/acc-provision --flavor=kubernetes-1.9 -a -u admin -p {{ aci_admin_pass }} -c /tmp/aci-provision.yml -o {{ kube_config_dir }}/aci_cni_config.yml
  when: inventory_hostname == groups['kube-master'][0]
  #Need to ignore errors as acc-provision will always complain about failing to create L3 OUT or simialr 
  ignore_errors: yes

- name: Start ACI CNI resources
  command: /usr/local/bin/kubectl apply -f "{{kube_config_dir}}/aci_cni_config.yml"
  when: inventory_hostname == groups['kube-master'][0]
